added index name tests

diff --git a/.github/workflows/automated_testing.yaml b/.github/workflows/automated_testing.yaml
--- a/.github/workflows/automated_testing.yaml
+++ b/.github/workflows/automated_testing.yaml
@@ -366,6 +366,21 @@ jobs:
         env:
           INPUT_SCHEMA: /tmp/openapi.json
           INPUT_JSONS: ${{ steps.create_json_validation_content.outputs.validation_file}}
+      - name: Validate Index Not starting with underscore
+        run: |
+          if [[ $(cat ${{ matrix.index }} | jq -r '.name' | egrep "^_") ]]
+          then
+            echo "[Error] - Indexes should not start with _"
+            exit 1
+          fi
+      - name: Validate Index Name
+        run: | 
+          # Index names must consist of only numbers, letters, periods, underscores, and hyphens. 
+         if [[ ! $(cat ${{ matrix.index }} | jq -r '.name' | egrep "^[A-Za-z\d\._-]+$") ]]
+         then
+          echo "[Error] - Index contains invalid characters"
+          exit 1
+        fi
   splunkbase_app_validation:
     needs: authenticate_with_splunk
     runs-on: ubuntu-latest
