hopefully this time

diff --git a/.github/workflows/ci_splunk_cloud.yaml b/.github/workflows/ci_splunk_cloud.yaml
--- a/.github/workflows/ci_splunk_cloud.yaml
+++ b/.github/workflows/ci_splunk_cloud.yaml
@@ -300,23 +300,23 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Check out repo code
         uses: actions/checkout@v3
-      - name: Authenticate with splunk API service
-        id: authenticate-splunk-api-service
-        env:
-          splunkbase_user: ${{ secrets.SPLUNKBASE_USERNAME}}
-          splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD}}
-        run: |
-          splunk_api_session=$(curl -s -k -u ${splunkbase_user}:${splunkbase_password} --url "https://api.splunk.com/2.0/rest/login/splunk")
-          if [[ $(echo ${splunk_api_session} | jq ".status_code") -eq 200 ]]
-          then 
-            echo "[success] - Obtained Auth Token from Splunk API service"
-            echo ${splunk_api_session} | jq ".data.token" | sed 's/\"//g' > /tmp/appInspect_token
-            echo "appInspect_token=$(cat /tmp/appInspect_token)" >> $GITHUB_OUTPUT
-          else
-            echo "[failed] - Something happened that resulted in a non-200 response"
-            echo "${splunk_api_session}"
-            exit 1
-          fi
+      #- name: Authenticate with splunk API service
+      #  id: authenticate-splunk-api-service
+      #  env:
+      #    splunkbase_user: ${{ secrets.SPLUNKBASE_USERNAME}}
+      #    splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD}}
+      #  run: |
+      #    splunk_api_session=$(curl -s -k -u ${splunkbase_user}:${splunkbase_password} --url "https://api.splunk.com/2.0/rest/login/splunk")
+      #    if [[ $(echo ${splunk_api_session} | jq ".status_code") -eq 200 ]]
+      #    then 
+      #      echo "[success] - Obtained Auth Token from Splunk API service"
+      #      echo ${splunk_api_session} | jq ".data.token" | sed 's/\"//g' > /tmp/appInspect_token
+      #      echo "appInspect_token=$(cat /tmp/appInspect_token)" >> $GITHUB_OUTPUT
+      #    else
+      #      echo "[failed] - Something happened that resulted in a non-200 response"
+      #      echo "${splunk_api_session}"
+      #      exit 1
+      #    fi
       - name: Gather installed private apps from stack
         env:
           stack: ${{ secrets.STACK_NAME}}
@@ -405,7 +405,7 @@ jobs:
         env:
           stack: ${{ secrets.STACK_NAME}}
           stack_jwt: ${{ secrets.STACK_TOKEN}}
-          appinspect_token: ${{ steps.auth-splunk-api.outputs.api_auth_token }}
+          appinspect_token: ${{ needs.authenticate_with_splunk.outputs.splunkapi_auth_token }}
         run: |
           mkdir -p /tmp/appinspect_failures
           cd /tmp/privatePackages
@@ -466,7 +466,7 @@ jobs:
           stack: ${{ secrets.STACK_NAME}}
           stack_jwt: ${{ secrets.STACK_TOKEN}}
           acs: staging.admin.splunk.com
-          appinspect_token: ${{ steps.auth-splunk-api.outputs.api_auth_token }}
+          appinspect_token: ${{ needs.authenticate_with_splunk.outputs.splunkapi_auth_token }}
         run: |
           #export acs="staging.admin.splunk.com"
           #export appinspect_token=$(cat /tmp/appInspect_token)
